name: 02 - Building Events
on: 
    push:
    pull_request:
    schedule:
      - cron: '0/5 * * * *'
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger 
        run: |
          echo "Triggering Event name: ${{ github.event_name }}"
